### ISSUE TITLE
Add more tests

### ISSUE THREAD

**Issue by robintw** [robintw/PandasToPowerpoint#4]
As suggested in your PR @fdosani

**Comment by fdosani** [comment]
Hi @robintw Just a QQ or my own understanding. Fair to say that `rounding` is never used?
https://github.com/robintw/PandasToPowerpoint/blob/master/pd2ppt/pd2ppt.py#L95
Doesn't seemed to be called anywhere.

**Comment by fdosani** [comment]
WIP branch here: https://github.com/fdosani/PandasToPowerpoint/tree/unit-testing
